-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b, BOOK_SALES bs
WHERE b.BOOK_ID = bs.BOOK_ID AND (YEAR(bs.SALES_DATE) = 2022 AND MONTH(bs.SALES_DATE) = 1)
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC